--거래 게시판
CREATE TABLE trade_board(
	NUM NUMBER PRIMARY KEY, --품목 번호
	WRITER VARCHAR2(100) NOT NULL, --판매자
	TITLE VARCHAR2(100) NOT NULL, -- 판매품목
	CONTENT CLOB, --판매 내용
	PRICE NUMBER(30) NOT NULL, --가격
	STATUS NUMBER(2) DEFAULT 0 NOT NULL, --판매유무
	REGDATE DATE, --날짜
	CATEGORY VARCHAR2(100) --카테고리
);
--거래 게시판 시퀀스
CREATE SEQUENCE trade_board_seq;

--거래 게시판 댓글
CREATE TABLE trade_board_comment(
	NUM NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(500),
	TARGET_ID VARCHAR2(100),
	REF_GROUP NUMBER,
	COMMENT_GROUP NUMBER,
	DELETED CHAR(3) DEFAULT 0,
	REGDATE DATE,
	SECRET NUMBER DEFAULT 0
);
--거래 게시판 댓글 시퀀스
CREATE SEQUENCE trade_board_comment_seq;

--공지 게시판 
CREATE TABLE notice_board(
	NUM NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT CLOB,
	REGDATE DATE,
	PIN NUMBER DEFAULT(0)
);
--공지 게시판 시퀀스
CREATE SEQUENCE notice_board_seq;

--공지 게시판 댓글
CREATE TABLE notice_board_comment(
	NUM NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(500),
	TARGET_ID VARCHAR2(100),
	REF_GROUP NUMBER,
	COMMENT_GROUP NUMBER,
	DELETED CHAR(3) DEFAULT(0),
	REGDATE DATE
);
--공지게시판 댓글 시퀀스
CREATE SEQUENCE notice_board_comment_seq;






